# Azure Pipeline for deploying a new version of the site
trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
- task: HugoTask@1
  inputs:
    source: '$(System.DefaultWorkingDirectory)/site'
    destination: '$(System.DefaultWorkingDirectory)/site/public'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Bit Badger Solutions(8d63f62c-4de2-4682-af66-5b44e7973fd6)'
    appType: 'webApp'
    WebAppName: 'bayvista'
    packageForLinux: '$(System.DefaultWorkingDirectory)/site/public'
