# Azure Pipeline for deploying a new version of the site
trigger:
- main

pool:
  vmImage: 'windows-2019'

steps:
- task: HugoTask@1
  displayName: Generate Site Via Hugo
  inputs:
    source: '$(System.DefaultWorkingDirectory)/site'
    destination: '$(System.DefaultWorkingDirectory)/site/public'

- task: AzureRmWebAppDeployment@4
  displayName: Depoly New Files to Azure App Service
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Bit Badger Service Connection'
    appType: 'webApp'
    WebAppName: 'bayvista'
    packageForLinux: '$(System.DefaultWorkingDirectory)/site/public'

- task: PurgeAzureCDNEndpoint@2
  displayName: Purge CDN Endpoint
  inputs:
    ConnectedServiceNameSelector: 'ConnectedServiceNameARM'
    ConnectedServiceNameARM: 'Bit Badger Service Connection'
    ResourceGroupName: 'BayVista'
    EndpointName: 'bayvista'
    ProfileName: 'bayvista-cdn'
    PurgeContent: '/*'
